export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_MY_PRODUCT = "GET_MY_PRODUCT";
export const FAIL_PRODUCT = "FAIL_PRODUCT";
